spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: '{cipher}7dc97ce72a55b33bbbae94298ec6869ef6c26c1d05085c3dc17d810eba395225'
  cloud:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}949246d7a24d771708e302ec1799a0bdbc590d374f43d8fa8540b583ba35f598'
order-service:
  uri: http://localhost:8000/order-service/%s/orders